# Generated by Django 3.2.6 on 2023-01-09 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUESTED', 'Запрос в обработке'), ('APPROVED', 'Принято'), ('REJECTED', 'Отклонено'), ('DELETED', 'Удален')], default='REQUESTED', max_length=255, verbose_name='Статус')),
                ('datetime_create', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('datetime_approve', models.DateTimeField(null=True, verbose_name='Дата добавления')),
                ('addressee_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receive_friends', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('requested_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friends', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
        ),
    ]
