"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 3.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

import environ

env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3(3h3c_4b%eagog3c^9+(4+-13%551&7#2%fa$xesy2325ep@6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# RabbitMQ settings
RABBITMQ_HOSTNAME = 'localhost'
RABBITMQ_PORT = 5672
RABBITMQ_USERNAME = 'guest'
RABBITMQ_PASSWORD = 'guest'

# SHUFTIPRO CREDENTIALS
SHUFTIPRO_CLIENT_ID = env('SHUFTIPRO_CLIENT_ID')
SHUFTIPRO_SECRET_KEY = env('SHUFTIPRO_SECRET_KEY')

SHUFTIPRO_TRANSACTION_TYPE = "test"

# MONETIX PAYMENT CREDENTIALS
MONETIX_PROJECT_ID = env('MONETIX_PROJECT_ID')
MONETIX_KEY = env('MONETIX_KEY')
HEALTH_CHECK_KEY = env('HEALTH_CHECK_KEY')
HEALTH_CHECK_LOGIN = env('HEALTH_CHECK_LOGIN')
HEALTH_CHECK_PASSWORD = env('HEALTH_CHECK_PASSWORD')

MONETIX_TRANSACTION_TYPE = "test"

# EMAIL CREDENTIALS
DEFAULT_FROM_EMAIL = 'cybert.helper@gmail.com'
SERVER_EMAIL = 'cybert.helper@gmail.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = env('EMAIL_HOST')
EMAIL_PORT = 587
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_USE_TLS = True
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')

# TWILIO sms provider API СREDENTIALS
# TWILIO_VERIFY = 'https://verify.twilio.com/v2/',
TWILIO_VERIFY_SERVICE_SID = env('TWILIO_VERIFY_SERVICE_SID')
TWILIO_ACCOUNT_SID = env('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = env('TWILIO_AUTH_TOKEN')
ACCOUNT_SECURITY_API_KEY = env('ACCOUNT_SECURITY_API_KEY')

ALLOWED_HOSTS = [
    'beta-cybert.kz',
    'api2.beta-cybert.kz',
    'api.beta-cybert.kz',
    'localhost',
    '127.0.0.1',
    'callback.paybox.money',
    'cybert.online',
    'api.cybert.online',
    'api2.cybert.online',
    '88.218.112.16',
    '88.218.113.16',
    '178.57.66.244',
    '3.65.185.232',
    '3.71.149.52',
    '15.161.172.14',
    '15.161.175.230',
    '16.170.89.23',
    '16.170.114.96',
    '178.57.67.0/24',
    '93.179.90.128/25',
    '93.179.91.0/24',
    '78.57.66.128/25',
    '1kz.site',
    '193.247.74.71',
    '172.27.0.6',
    '193.247.74.203',
    'api.opendota.com'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_celery_results',
    'drf_yasg',
    # django-addons
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django.contrib.sites',
    'django_extensions',

    # user added apps
    'authentication',
    'authentication.verification',
    'achievements',
    'community',
    # 'payments.paybox.apps.PayboxConfig',
    'payments.monetix',
    'dota',
    'dota.report',
    'chat',
    'payments.paybox',
    'sitestatus',
    'accounting',

    # add django channels
    'channels',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# add this block below MIDDLEWARE
CORS_ORIGIN_ALLOW_ALL = True
# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# CORS_ALLOWED_ORIGIN_REGEXES = [
#     'beta-cybert.kz',
#     'http://127.0.0.1:3000',
#     'http://localhost:3000',
#     'https://api.beta-cybert.kz',
#     'https://api2.beta-cybert.kz',
#     'https://cybert.online',
#     'https://api.cybert.online',
#     'https://api2.cybert.online',
#     'https://88.218.112.16',
#     'https://88.218.113.16',
#     'https://178.57.66.244',
#     'https://3.65.185.232',
#     'https://3.71.149.52',
#     'https://15.161.172.14',
#     'https://15.161.175.230',
#     'https://16.170.89.23',
#     'https://16.170.114.96',
#     'https://1kz.site',
#     'https://193.247.74.71',
#     'https://193.247.74.203'
# ]

# CORS_ORIGIN_WHITELIST = (
#     'https://beta-cybert.kz',
#     'http://127.0.0.1:3000',
#     'http://localhost:3000',
#     'https://api.beta-cybert.kz',
#     'https://api2.beta-cybert.kz',
#     'https://cybert.online',
#     'https://api.cybert.online',
#     'https://api2.cybert.online',
#     'https://88.218.112.16',
#     'https://88.218.113.16',
#     'https://178.57.66.244',
#     'https://3.65.185.232',
#     'https://3.71.149.52',
#     'https://15.161.172.14',
#     'https://15.161.175.230',
#     'https://16.170.89.23',
#     'https://16.170.114.96',
#     'https://1kz.site',
#     'https://193.247.74.71',
#     'https://193.247.74.203'
# )
# CORS_ALLOWED_ORIGINS = [
#     '*'
#     # 'https://beta-cybert.kz',
#     # 'http://127.0.0.1:3000',
#     # 'http://localhost:3000',
#     # 'https://api.beta-cybert.kz',
#     # 'https://api2.beta-cybert.kz',
#     # 'https://cybert.online',
#     # 'https://api.cybert.online',
#     # 'https://api2.cybert.online',
#     # 'https://88.218.112.16',
#     # 'https://88.218.113.16',
#     # 'https://178.57.66.244',
#     # 'https://3.65.185.232',
#     # 'https://3.71.149.52',
#     # 'https://15.161.172.14',
#     # 'https://15.161.175.230',
#     # 'https://16.170.89.23',
#     # 'https://16.170.114.96',
#     # 'https://1kz.site',
#     # 'https://193.247.74.71',
#     # 'https://193.247.74.203'
# ]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'back/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'cybert_db',
        'USER': 'zhancare',
        'PASSWORD': '4HPzQt2HyU',
        'HOST': 'localhost',
        'PORT': '5432',
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': env('DB_NAME'),
    #     'USER': env('DB_USER'),
    #     'PASSWORD': env('DB_PASSWORD'),
    #     'HOST': env('DB_HOST'),
    #     'PORT': env('DB_PORT'),
    #     'CONN_MAX_AGE': 3600,
    #     'OPTIONS': {
    #         'init_command': "SET sql_mode='STRICT_TRANS_TABLES', innodb_strict_mode=1;",
    #         'charset': 'utf8mb4',
    #         'use_unicode': True,
    #     }
    # }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

# USE_L10N = True  # Removed in Django 5.0 - localization is now always enabled

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
# add the following just below STATIC_URL
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

CELERY_BROKER_URL = "redis://redis:6379"
CELERY_RESULT_BACKEND = "django-db"
CELERY_RESULT_EXTENDED = True
CELERY_TACKS_LATE = True
CELERY_TASK_TRACK_STARTED = True
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
ACHIEVEMENT_USE_CELERY = True

AUTH_USER_MODEL = 'authentication.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
)

# FRONTEND_HOST = 'http://localhost:3000'
FRONTEND_HOST = 'https://cybert.online'

# BACKEND_HOST = 'http://localhost:8000'
BACKEND_HOST = 'https://api.cybert.online'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            # 'hosts': [('localhost', 6379)]
            'hosts': [('redis', 6379)]
        }
    }
}

# Commented out custom ensure_connection to fix PostgreSQL transaction issues
# for name, config in settings.DATABASES.items():
#     module = importlib.import_module(config["ENGINE"] + ".base")
#
#
#     def ensure_connection(self):
#         if self.connection is not None:
#             try:
#                 with CursorWrapper(self.create_cursor(), self) as cursor:
#                     cursor.execute("SELECT 1")
#                 return
#             except Exception as exception:
#                 print("SQL CONNECTION something go wrong : %s " % exception)
#                 pass
#
#         with self.wrap_database_errors:
#             print("Reconnect?")
#             self.connect()
#
#
#     module.DatabaseWrapper.ensure_connection = ensure_connection
