# Generated by Django 3.2.6 on 2023-01-09 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('card_holder', models.CharField(blank=True, max_length=150, null=True)),
                ('expiry_month', models.CharField(blank=True, max_length=5, null=True)),
                ('expiry_year', models.CharField(blank=True, max_length=5, null=True)),
                ('token', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(blank=True, default=0, null=True)),
                ('bonus_balance', models.FloatField(blank=True, default=0, null=True)),
                ('blocked_balance', models.FloatField(blank=True, default=0, null=True)),
                ('last_refill', models.DateTimeField(auto_now=True, null=True)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('RUB', 'RUB'), ('KZT', 'KZT')], default='USD', max_length=100)),
                ('language_payments', models.CharField(choices=[('en', 'en'), ('ru', 'ru'), ('kk', 'kk')], default='en', max_length=100)),
                ('accounts', models.ManyToManyField(blank=True, default=None, to='monetix.UserAccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletException',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.TextField(blank=True, default='', null=True)),
                ('exception', models.TextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('pay_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('user_account', models.ManyToManyField(blank=True, default=None, to='monetix.UserAccount')),
                ('user_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monetix.userwallet')),
            ],
        ),
        migrations.AddField(
            model_name='userwallet',
            name='wallet_history',
            field=models.ManyToManyField(blank=True, default=None, to='monetix.WalletHistory'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='user_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monetix.userwallet'),
        ),
    ]
