# Generated by Django 3.2.6 on 2023-01-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetix', '0002_alter_userwallet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('UAH', 'UAH'), ('RUB', 'RUB'), ('KZT', 'KZT')], default='USD', max_length=100),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='language_payments',
            field=models.CharField(choices=[('en', 'en'), ('ua', 'ua'), ('ru', 'ru'), ('kk', 'kk')], default='en', max_length=100),
        ),
    ]
