# Generated by Django 3.2.6 on 2023-01-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetix', '0003_auto_20230123_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('UAH', 'UAH'), ('RUB', 'RUB'), ('KZT', 'KZT'), ('UZS', 'UZS')], default='USD', max_length=100),
        ),
    ]
