# Generated by Django 3.2.6 on 2023-01-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetix', '0004_auto_20230127_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='language_payments',
            field=models.CharField(choices=[('en', 'en'), ('ua', 'ua'), ('ru', 'ru'), ('kk', 'kk'), ('uz', 'uz')], default='en', max_length=100),
        ),
    ]
