# Generated by Django 3.2.6 on 2023-05-19 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monetix', '0005_alter_userwallet_language_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('user_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monetix.userwallet')),
            ],
        ),
        migrations.AddField(
            model_name='userwallet',
            name='binance_accounts',
            field=models.ManyToManyField(blank=True, default=None, to='monetix.UserBinanceAccount'),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='user_binance_account',
            field=models.ManyToManyField(blank=True, default=None, to='monetix.UserBinanceAccount'),
        ),
    ]
