# Generated by Django 3.2.6 on 2023-05-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monetix', '0006_auto_20230519_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='payout_commission',
            field=models.FloatField(blank=True, default=5.0, null=True),
        ),
        migrations.AddField(
            model_name='wallethistory',
            name='payout_commission',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
