# Generated by Django 3.2.6 on 2023-01-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='online_status',
            field=models.CharField(choices=[('ONLINE', 'В сети'), ('OFFLINE', 'Не в сети')], default='ONLINE',
                                   max_length=255),
        ),
    ]
