# Generated by Django 3.2.6 on 2023-01-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0003_customuser_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='document_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='face_match_confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='gender',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='userverification',
            name='individual_identification_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
