# Generated by Django 3.2.6 on 2023-01-10 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0004_auto_20230110_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='verification',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='authentication.userverification'),
        ),
    ]
