# Generated by Django 3.2.6 on 2023-01-11 02:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('authentication', '0006_alter_userverification_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationhistory',
            name='user_verification',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification',
        ),
        migrations.DeleteModel(
            name='UserVerification',
        ),
        migrations.DeleteModel(
            name='VerificationHistory',
        ),
    ]
