# Generated by Django 3.2.6 on 2023-01-11 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('verification', '0001_initial'),
        ('authentication', '0007_auto_20230111_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='verification.userverification'),
        ),
    ]
