# Generated by Django 3.2.6 on 2023-01-14 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monetix', '0002_alter_userwallet_user'),
        ('authentication', '0008_customuser_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_wallet',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='user_wallet', to='monetix.userwallet'),
        ),
    ]
