# Generated by Django 3.2.6 on 2023-01-09 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dota', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hero_id', models.IntegerField(blank=True, null=True)),
                ('steam_id', models.CharField(blank=True, max_length=100, null=True)),
                ('steam_id_converted', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.CharField(choices=[('None', 'None'), ('not guilty', 'Not guilty'), ('guilty', 'Guilty')], default='None', max_length=100)),
                ('datetime_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_create_game_time', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime_finish', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_reported', to=settings.AUTH_USER_MODEL)),
                ('user_reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reported', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportLobby',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.CharField(choices=[('None', 'None'), ('unlock', 'Finish game'), ('cancel', 'Cancel game')], default='None', max_length=100)),
                ('datetime_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_finish', models.DateTimeField(blank=True, null=True)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dota.lobby')),
                ('reported_members', models.ManyToManyField(blank=True, default=None, to='report.ReportUser')),
            ],
        ),
    ]
