# Generated by Django 3.2.6 on 2023-01-09 20:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bot_name', models.CharField(default=None, max_length=150, null=True)),
                ('bot_password', models.CharField(default=None, max_length=100, null=True)),
                ('bot_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_game', models.DateTimeField(auto_now_add=True)),
                ('finish_game', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('lobby_lvl', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('is_block', models.BooleanField(blank=True, default=None, null=True)),
                ('bet', models.IntegerField(default=None, null=True)),
                ('match_id', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_start_game', models.DateTimeField(blank=True, null=True)),
                ('datetime_finish_game', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Pending', 'Pending'), ('Game started', 'Game started'), ('Finished', 'Finished'), ('Error', 'Error')], default='Created', max_length=100)),
                ('slots', models.IntegerField(choices=[(2, '1v1'), (10, '5v5')], default=2)),
                ('game_mode', models.CharField(choices=[('All Pick', 'All Pick'), ('1v1 Solo Mid', '1v1 Solo Mid'), ('Captains Mode', 'Captains Mode')], default='All Pick', max_length=100)),
                ('game_history', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='dota.gamehistory')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('steam_id', models.CharField(blank=True, max_length=100, null=True)),
                ('hero_id', models.IntegerField(blank=True, null=True)),
                ('team', models.CharField(choices=[('1', 'Team 1'), ('2', 'Team 2')], default='1', max_length=1, null=True)),
                ('game_team', models.CharField(default=None, max_length=50, null=True)),
                ('game_name', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('player_info', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dota.playerinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='rate',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dota.rating'),
        ),
        migrations.AddField(
            model_name='playerinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(choices=[('1', 'Team 1'), ('2', 'Team 2')], default='1', max_length=1, null=True)),
                ('status', models.BooleanField(default=False)),
                ('leader', models.BooleanField(default=False)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='dota.lobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team'],
            },
        ),
        migrations.AddField(
            model_name='lobby',
            name='members',
            field=models.ManyToManyField(through='dota.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='lobby_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dota.lobby'),
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='players_info',
            field=models.ManyToManyField(blank=True, default=None, to='dota.PlayerInfo'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('rate__range', (1, 5))), name='valid_rate'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'player_info'), name='rating_once'),
        ),
    ]
