# Generated by Django 3.2.6 on 2023-02-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='task_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
