# Generated by Django 3.2.18 on 2023-03-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0002_lobby_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
