# Generated by Django 3.2.18 on 2023-03-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0003_membership_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='position',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
