# Generated by Django 3.2.6 on 2023-05-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0004_lobby_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinfo',
            name='game_commission',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
