# Generated by Django 4.2.30 on 2026-04-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dota', '0005_playerinfo_game_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='vs_bots',
            field=models.BooleanField(default=False),
        ),
    ]
